package icons;

import javax.swing.Icon;

import com.intellij.openapi.util.IconLoader;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class CucumberIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, CucumberIcons.class);
  }

  public static final Icon Cucumber = load("/org/jetbrains/plugins/cucumber/icons/cucumber.png"); // 16x16
  public static final Icon Steps_group_closed = load("/org/jetbrains/plugins/cucumber/icons/steps_group_closed.png"); // 16x16
}
