package icons;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class CucumberIcons {
  private static Image load(String path) {
    return IconLoader.getIcon(path, CucumberIcons.class);
  }

  public static final Image Cucumber = load("/org/jetbrains/plugins/cucumber/icons/cucumber.png"); // 16x16
  public static final Image Steps_group_closed = load("/org/jetbrains/plugins/cucumber/icons/steps_group_closed.png"); // 16x16
}
